### ISSUE TITLE
Alexasmartcli.py start issue

### ISSUE THREAD

**Issue by chubs168** [eclair4151/AlexaControlledSamsungTV#11]
Sorry new to this.  When i run the alexasmartcli.py it won't run. When i run it in python i get the following.
 %Run alexasmartcli.py
please specify an action
Traceback (most recent call last):
  File "/home/pi/alexacontrolledsamsungtv/alexasmartcli.py", line 36, in <module>
    exit()
  File "/usr/lib/python3.5/_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: None
Did i install something wrong? 
Thanks

**Comment by eclair4151** [comment]
what are you trying to do? you have to pass in an argument.  ex:

python3 alexasmartcli.py scan
python3 alexasmartcli.py login
python3 alexasmartcli.py register
python3 alexasmartcli.py setup_cable
python3 alexasmartcli.py start

**Comment by chubs168** [comment]
sorry bad example. I think I have one everything correct but when I go to run it I get the following. Did i miss a step.
pi@raspberrypi:~/alexacontrolledsamsungtv $ python3 alexasmartcli.py start
starting server...
 (most recent call last):
  File "alexasmartcli.py", line 181, in <module>
    mqtt_server.startServer(options.mute)
  File "/home/pi/alexacontrolledsamsungtv/helpers/mqtt_server.py", line 235, in startServer
    myMQTTClient.connect()
  File "/home/pi/.local/lib/python3.5/site-packages/AWSIoTPythonSDK/MQTTLib.py", line 408, in connect
    return self._mqtt_core.connect(keepAliveIntervalSecond)
  File "/home/pi/.local/lib/python3.5/site-packages/AWSIoTPythonSDK/core/protocol/mqtt_core.py", line 168, in connect
    self.connect_async(keep_alive_sec, self._create_blocking_ack_callback(event))
  File "/home/pi/.local/lib/python3.5/site-packages/AWSIoTPythonSDK/core/protocol/mqtt_core.py", line 179, in connect_async
    rc = self._internal_async_client.connect(keep_alive_sec, ack_callback)
  File "/home/pi/.local/lib/python3.5/site-packages/AWSIoTPythonSDK/core/protocol/internal/clients.py", line 113, in connect
    rc = self._paho_client.connect(host, port, keep_alive_sec)
  File "/home/pi/.local/lib/python3.5/site-packages/AWSIoTPythonSDK/core/protocol/paho/client.py", line 654, in connect
    return self.reconnect()
  File "/home/pi/.local/lib/python3.5/site-packages/AWSIoTPythonSDK/core/protocol/paho/client.py", line 776, in reconnect
    sock = socket.create_connection((self._host, self._port), source_address=(self._bind_address, 0))
  File "/usr/lib/python3.5/socket.py", line 694, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.5/socket.py", line 733, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

do this tell you anything?

**Comment by eclair4151** [comment]
It’s most likely a DNS issue. See https://github.com/eclair4151/AlexaControlledSamsungTV/issues/6
