### ISSUE TITLE
Error when searching for tv

### ISSUE THREAD

**Issue by judgeyuk** [eclair4151/AlexaControlledSamsungTV#26]
Hey i get the below when scanning for my tv its a 2019 qled

During handling of the above exception, another exception occurred:

```
Traceback (most recent call last):
  File "alexasmartcli.py", line 57, in <module>
    tvs = scan_network_ssdp(True, wait=2)
  File "/home/pi/AlexaControlledSamsungTV/helpers/ssdp.py", line 79, in scan_network_ssdp
    info = getTVinfo(tv.location)
  File "/home/pi/AlexaControlledSamsungTV/helpers/ssdp.py", line 117, in getTVinfo
    resp = requests.get('http://' + ip.group(0) + ':8001/api/v2/').json()
  File "/usr/lib/python3/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='192.168.171.5', port=8001): Max retries exceeded with url: /api/v2/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb64bda70>: Failed to establish a new connection: [Errno 111] Connection refused'))
pi@raspberrypi:~/AlexaControlledSamsungTV $
```

**Comment by eclair4151** [comment]
Yea there are a few issues with the scan command i need to make it more reliable. in the meantime you dont actually need the scan command, That was just for convenience of finding the ip/macaddress/version 
For now feel free to find that info manually from the tv settings and put it in the config file yourself

**Comment by judgeyuk** [comment]
Thank you working great
